---
title: "Plots and Stats - VR"
output: html_notebook
---

Build Plots and Stats for the CEM data

Step 1: Scale to the 99% cumulative density estimate
Step 2: Take out 0s
Step 3: Compare using ks test

```{r}
# Libraries
library(tidyverse)
library(reshape)
```

# Load Contaminant Data
```{r}
# Contaminant Data
collect<-read.csv("../../data/true_contam/RigFishBioAccum-summary.csv")
collect<-collect[which(collect$X.SCIENTIFIC.NAME == 'Sebastes miniatus'  & 
                         collect$SAMPLING.POINT == "RF1"),]
colnames(collect)[16:17] <- c("DDT","PCB")
```

# DDT 
## OCSD Data - Tissue
```{r}
# Tissue
filtered <- collect %>%
  filter(!is.na(DDT)) 

dataset <- filtered$DDT

# Find 99% quantile for scaling and scale
upper <- quantile(dataset, 0.99)
scaled <- dataset/upper

# Save for later
ddt_tissue <- scaled

# Create histogram
field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
field_plot <- as.data.frame(table(field_plot))
colnames(field_plot)[1] <- "value"
field_plot$value <- as.numeric(paste(field_plot$value))
field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)

plot_this<-as.data.frame(seq(0,1.5,0.1))
colnames(plot_this)<-"x"
plot_this$value<-0
for( i in 1:nrow(plot_this)) { 
  if (plot_this$x[i] %in% field_plot$value) {
    plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
  } 
}

zeros <- plot_this[which(plot_this$x  == 0),]
others <- plot_this[which(plot_this$x != 0),]

barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="darkslategray", ylim=c(0,1),
        xlab=expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))),
        ylab="Proportion of Fish", 
        main=expression(paste(plain("["),Sigma,plain("DDT] in Muscle Tissue"))))

title(main=paste("n =", length(scaled)), line=-1, font.main=1)

barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)

# save plot
filename <- "ddt_muscle"
png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
par(mar=c(3.5,3.5,2,1), cex=3)
barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="darkslategray", ylim=c(0,1))
title(main=expression(paste(plain("["),Sigma,plain("DDT] in Muscle Tissue"))), line=0, font.main=1)
title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
mtext(expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))), side=1, line=2, cex=3)
mtext("Proportion of Fish", side=2, line=2, cex=3)

barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
dev.off()
```

## CEM Generated Files
```{r}
# List of relevant files for DDT and VR
list_files <- list.files('../../data/CEMs/', pattern='ddt')
list_files <- list_files[grepl('scaled_VR', list_files)]

for( file in list_files ) { 
  dat <- read.csv(paste0('../../data/CEMS/', file))
  
  # First run will be without behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-noscale")
  
  dataset <- dat$tox_peryear_noscaler[which(!is.infinite(dat$tox_peryear_noscaler) & !(is.nan(dat$tox_peryear_noscaler)))]
  
  # Find 99% quantile for scaling and scale
  upper <- quantile(dataset, 0.99)
  scaled <- dataset/upper
  
  # Save for later
  assign(name, scaled)
  
  # Create histogram
  field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
  field_plot <- as.data.frame(table(field_plot))
  colnames(field_plot)[1] <- "value"
  field_plot$value <- as.numeric(paste(field_plot$value))
  field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)
  
  plot_this<-as.data.frame(seq(0,1.5,0.1))
  colnames(plot_this)<-"x"
  plot_this$value<-0
  for( i in 1:nrow(plot_this)) { 
    if (plot_this$x[i] %in% field_plot$value) {
      plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
    } 
  }
  
  zeros <- plot_this[which(plot_this$x  == 0),]
  others <- plot_this[which(plot_this$x != 0),]
  
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1),
          xlab=expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))),
          ylab="Proportion of Fish", 
          main=expression(paste(plain("CEM ["),Sigma,plain("DDT] without behavioral data"))))
  
  title(main=paste("Rate =", strsplit(name, "m")[[1]][1],
                   "m/min; Time Interpolation =", strsplit(name, "min-")[[1]][2], "min"),
        line=-1, font.main=1)
  title(main=paste("n =", length(scaled)), line=-3, font.main=1)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)
  
  # save plot
  filename <- paste0(name,"_ddt_no-behavioral")
  png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
  par(mar=c(3.5,3.5,2,1), cex=3)
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1))
  title(main=expression(paste(plain("["),Sigma,plain("DDT] without behavioral data"))), line=0,
        font.main=1)
  title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
  mtext(expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))), side=1, line=2, cex=3)
  mtext("Proportion of Fish", side=2, line=2, cex=3)
  
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
  dev.off()
  
  # Second run will be with behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-scale")
  
  dataset <- dat$tox_peryear_scaled[which(!is.infinite(dat$tox_peryear_scaled) & !(is.nan(dat$tox_peryear_scaled)))]
  
  # Find 99% quantile for scaling and scale
  upper <- quantile(dataset, 0.99)
  scaled <- dataset/upper
  
  # Save for later
  assign(name, scaled)
  
  # Create histogram
  field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
  field_plot <- as.data.frame(table(field_plot))
  colnames(field_plot)[1] <- "value"
  field_plot$value <- as.numeric(paste(field_plot$value))
  field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)
  
  plot_this<-as.data.frame(seq(0,1.5,0.1))
  colnames(plot_this)<-"x"
  plot_this$value<-0
  for( i in 1:nrow(plot_this)) { 
    if (plot_this$x[i] %in% field_plot$value) {
      plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
    } 
  }
  
  zeros <- plot_this[which(plot_this$x  == 0),]
  others <- plot_this[which(plot_this$x != 0),]
  
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1),
          xlab=expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))),
          ylab="Proportion of Fish", 
          main=expression(paste(plain("CEM ["),Sigma,plain("DDT] with behavioral data"))))
  
  title(main=paste("Rate =", strsplit(name, "m")[[1]][1],
                   "m/min; Time Interpolation =", strsplit(name, "min-")[[1]][2], "min"),
        line=-1, font.main=1)
  title(main=paste("n =", length(scaled)), line=-3, font.main=1)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)
  
  # save plot
  filename <- paste0(name,"_ddt_behavioral")
  png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
  par(mar=c(3.5,3.5,2,1), cex=3)
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1))
  title(main=expression(paste(plain("["),Sigma,plain("DDT] with behavioral data"))), line=0,
        font.main=1)
  title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
  mtext(expression(paste(plain("Scaled ["),Sigma,plain("DDT]"))), side=1, line=2, cex=3)
  mtext("Proportion of Fish", side=2, line=2, cex=3)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
  dev.off()
}
```

## Run the KS tests
```{r} 
# With Zeros included for comparison

# Muscle vs all model runs
ks.test(ddt_tissue, `1mpermin-2min-noscale`)
ks.test(ddt_tissue, `1mpermin-5min-noscale`)
ks.test(ddt_tissue, `3mpermin-2min-noscale`)
ks.test(ddt_tissue, `3mpermin-5min-noscale`)
ks.test(ddt_tissue, `1mpermin-2min-scale`)
ks.test(ddt_tissue, `1mpermin-5min-scale`)
ks.test(ddt_tissue, `3mpermin-2min-scale`)
ks.test(ddt_tissue, `3mpermin-5min-scale`)
```

```{r}
# Without Zeros included for comparison

ddt_tissue_z <- ddt_tissue[ddt_tissue > 0]
`1mpermin-2min-noscale` <- `1mpermin-2min-noscale`[`1mpermin-2min-noscale` > 0]
`1mpermin-5min-noscale` <- `1mpermin-5min-noscale`[`1mpermin-5min-noscale` > 0]
`3mpermin-2min-noscale` <- `3mpermin-2min-noscale`[`3mpermin-2min-noscale` > 0]
`3mpermin-5min-noscale` <- `3mpermin-5min-noscale`[`3mpermin-5min-noscale` > 0]
`1mpermin-2min-scale` <- `1mpermin-2min-scale`[`1mpermin-2min-scale` > 0]
`1mpermin-5min-scale` <- `1mpermin-5min-scale`[`1mpermin-5min-scale` > 0]
`3mpermin-2min-scale` <- `3mpermin-2min-scale`[`3mpermin-2min-scale` > 0]
`3mpermin-5min-scale` <- `3mpermin-5min-scale`[`3mpermin-5min-scale` > 0]

# Muscle vs all model runs
ks.test(ddt_tissue, `1mpermin-2min-noscale`)
ks.test(ddt_tissue, `1mpermin-5min-noscale`)
ks.test(ddt_tissue, `3mpermin-2min-noscale`)
ks.test(ddt_tissue, `3mpermin-5min-noscale`)
ks.test(ddt_tissue, `1mpermin-2min-scale`)
ks.test(ddt_tissue, `1mpermin-5min-scale`)
ks.test(ddt_tissue, `3mpermin-2min-scale`)
ks.test(ddt_tissue, `3mpermin-5min-scale`)
```

# PCB
## OCSD Data - Tissue
```{r}
# Tissue
filtered <- collect %>%
  filter(!is.na(PCB)) 

dataset <- filtered$PCB

# Find 99% quantile for scaling and scale
upper <- quantile(dataset, 0.99)
scaled <- dataset/upper

# Save for later
pcb_tissue <- scaled

# Create histogram
field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
field_plot <- as.data.frame(table(field_plot))
colnames(field_plot)[1] <- "value"
field_plot$value <- as.numeric(paste(field_plot$value))
field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)

plot_this<-as.data.frame(seq(0,1.5,0.1))
colnames(plot_this)<-"x"
plot_this$value<-0
for( i in 1:nrow(plot_this)) { 
  if (plot_this$x[i] %in% field_plot$value) {
    plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
  } 
}

zeros <- plot_this[which(plot_this$x  == 0),]
others <- plot_this[which(plot_this$x != 0),]

barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="darkslategray", ylim=c(0,1),
        xlab=expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))),
        ylab="Proportion of Fish", 
        main=expression(paste(plain("["),Sigma,plain("PCB] in Muscle Tissue"))))

title(main=paste("n =", length(scaled)), line=-1, font.main=1)

barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)

# save plot
filename <- "pcb_muscle"
png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
par(mar=c(3.5,3.5,2,1), cex=3)
barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="darkslategray", ylim=c(0,1))
title(main=expression(paste(plain("["),Sigma,plain("PCB] in Muscle Tissue"))), line=0, font.main=1)
title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
mtext(expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))), side=1, line=2, cex=3)
mtext("Proportion of Fish", side=2, line=2, cex=3)

barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
dev.off()
```

## CEM Generated Files
```{r}
# List of relevant files for PCB and VR
list_files <- list.files('../../data/CEMs/', pattern='pcb')
list_files <- list_files[grepl('scaled_VR', list_files)]

for( file in list_files ) { 
  dat <- read.csv(paste0('../../data/CEMS/', file))
  
  # First run will be without behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-noscale")
  
  dataset <- dat$tox_peryear_noscaler[which(!is.infinite(dat$tox_peryear_noscaler) & !(is.nan(dat$tox_peryear_noscaler)))]
  
  # Find 99% quantile for scaling and scale
  upper <- quantile(dataset, 0.99)
  scaled <- dataset/upper
  
  # Save for later
  assign(name, scaled)
  
  # Create histogram
  field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
  field_plot <- as.data.frame(table(field_plot))
  colnames(field_plot)[1] <- "value"
  field_plot$value <- as.numeric(paste(field_plot$value))
  field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)
  
  plot_this<-as.data.frame(seq(0,1.5,0.1))
  colnames(plot_this)<-"x"
  plot_this$value<-0
  for( i in 1:nrow(plot_this)) { 
    if (plot_this$x[i] %in% field_plot$value) {
      plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
    } 
  }
  
  zeros <- plot_this[which(plot_this$x  == 0),]
  others <- plot_this[which(plot_this$x != 0),]
  
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1),
          xlab=expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))),
          ylab="Proportion of Fish", 
          main=expression(paste(plain("CEM ["),Sigma,plain("PCB] without behavioral data"))))
  
  title(main=paste("Rate =", strsplit(name, "m")[[1]][1],
                   "m/min; Time Interpolation =", strsplit(name, "min-")[[1]][2], "min"),
        line=-1, font.main=1)
  title(main=paste("n =", length(scaled)), line=-3, font.main=1)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)
  
  # save plot
  filename <- paste0(name,"_pcb_no-behavioral")
  png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
  par(mar=c(3.5,3.5,2,1), cex=3)
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1))
  title(main=expression(paste(plain("["),Sigma,plain("PCB] without behavioral data"))), line=0,
        font.main=1)
  title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
  mtext(expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))), side=1, line=2, cex=3)
  mtext("Proportion of Fish", side=2, line=2, cex=3)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
  dev.off()
  
  # Second run will be with behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-scale")
  
  dataset <- dat$tox_peryear_scaled[which(!is.infinite(dat$tox_peryear_scaled) & !(is.nan(dat$tox_peryear_scaled)))]
  
  # Find 99% quantile for scaling and scale
  upper <- quantile(dataset, 0.99)
  scaled <- dataset/upper
  
  # Save for later
  assign(name, scaled)
  
  # Create histogram
  field_plot <- data.frame("value"=ceiling(scaled/0.1)*0.1)
  field_plot <- as.data.frame(table(field_plot))
  colnames(field_plot)[1] <- "value"
  field_plot$value <- as.numeric(paste(field_plot$value))
  field_plot$Freq <- field_plot$Freq/sum(field_plot$Freq)
  
  plot_this<-as.data.frame(seq(0,1.5,0.1))
  colnames(plot_this)<-"x"
  plot_this$value<-0
  for( i in 1:nrow(plot_this)) { 
    if (plot_this$x[i] %in% field_plot$value) {
      plot_this$value[i]<-field_plot$Freq[which(field_plot$value == plot_this$x[i])]
    } 
  }
  
  zeros <- plot_this[which(plot_this$x  == 0),]
  others <- plot_this[which(plot_this$x != 0),]
  
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1),
          xlab=expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))),
          ylab="Proportion of Fish", 
          main=expression(paste(plain("CEM ["),Sigma,plain("PCB] with behavioral data"))))
  
  title(main=paste("Rate =", strsplit(name, "m")[[1]][1],
                   "m/min; Time Interpolation =", strsplit(name, "min-")[[1]][2], "min"),
        line=-1, font.main=1)
  title(main=paste("n =", length(scaled)), line=-3, font.main=1)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE)
  
  # save plot
  filename <- paste0(name,"_pcb_behavioral")
  png(paste0("../../figures/VR/raw_figures/", filename, ".png"),  height=480*8, width=480*11,  res=72*6)
  par(mar=c(3.5,3.5,2,1), cex=3)
  barplot(height=c(0, others$value), names.arg = seq(0,1.5,0.1), col="dodgerblue4", ylim=c(0,1))
  title(main=expression(paste(plain("["),Sigma,plain("PCB] with behavioral data"))), line=0,
        font.main=1)
  title(main=paste("n =", length(scaled)), line=-1.5, font.main=1)
  mtext(expression(paste(plain("Scaled ["),Sigma,plain("PCB]"))), side=1, line=2, cex=3)
  mtext("Proportion of Fish", side=2, line=2, cex=3)
  barplot(height=c(zeros$value, rep(0.0, 15)), col="lightgray", add=TRUE, xaxt="n", yaxt="n")
  dev.off()
}
```

## Run the KS tests
```{r} 
# With Zeros included for comparison

# Tissue vs all model runs
ks.test(pcb_tissue, `1mpermin-2min-noscale`)
ks.test(pcb_tissue, `1mpermin-5min-noscale`)
ks.test(pcb_tissue, `3mpermin-2min-noscale`)
ks.test(pcb_tissue, `3mpermin-5min-noscale`)
ks.test(pcb_tissue, `1mpermin-2min-scale`)
ks.test(pcb_tissue, `1mpermin-5min-scale`)
ks.test(pcb_tissue, `3mpermin-2min-scale`)
ks.test(pcb_tissue, `3mpermin-5min-scale`)
```

```{r}
# Without Zeros included for comparison

pcb_tissue_z <- pcb_tissue[pcb_tissue > 0]
`1mpermin-2min-noscale` <- `1mpermin-2min-noscale`[`1mpermin-2min-noscale` > 0]
`1mpermin-5min-noscale` <- `1mpermin-5min-noscale`[`1mpermin-5min-noscale` > 0]
`3mpermin-2min-noscale` <- `3mpermin-2min-noscale`[`3mpermin-2min-noscale` > 0]
`3mpermin-5min-noscale` <- `3mpermin-5min-noscale`[`3mpermin-5min-noscale` > 0]
`1mpermin-2min-scale` <- `1mpermin-2min-scale`[`1mpermin-2min-scale` > 0]
`1mpermin-5min-scale` <- `1mpermin-5min-scale`[`1mpermin-5min-scale` > 0]
`3mpermin-2min-scale` <- `3mpermin-2min-scale`[`3mpermin-2min-scale` > 0]
`3mpermin-5min-scale` <- `3mpermin-5min-scale`[`3mpermin-5min-scale` > 0]

# Tissue vs all model runs
ks.test(pcb_tissue, `1mpermin-2min-noscale`)
ks.test(pcb_tissue, `1mpermin-5min-noscale`)
ks.test(pcb_tissue, `3mpermin-2min-noscale`)
ks.test(pcb_tissue, `3mpermin-5min-noscale`)
ks.test(pcb_tissue, `1mpermin-2min-scale`)
ks.test(pcb_tissue, `1mpermin-5min-scale`)
ks.test(pcb_tissue, `3mpermin-2min-scale`)
ks.test(pcb_tissue, `3mpermin-5min-scale`)
```
