---
title: "Plots and Stats - VR"
output: html_notebook
---

Build Plots and Stats for the CEM data

Step 1: Scale to the median
Step 2: Fit to zscore of best fitting distribution
Step 3: Compare using ks test


```{r}
# Libraries
library(tidyverse)
library(reshape)
library(limma)

source("../functions/comparing-functions.R")
```

# Load Contaminant Data
```{r}
# Contaminant Data
collect<-read.csv("../../data/true-contaminants/vermilion_rockfish_contaminants.csv")
```

# DDT 
## OCSD Data - Tissue
```{r}
# Tissue
filtered <- collect %>%
  filter(!is.na(DDT)) 

dataset <- filtered$DDT

if(median(dataset) != 0) { 

# Scale to median
scaled <- dataset/median(dataset)

# Create Plot
create_plots(data = scaled, type = "in Muscle Tissue", contam = "DDT", 
             color = "darkslategray", path = "../../figures/vermilion-rockfish/", 
             file = "ddt_muscle")

# scale for ks test

ddt_tissue <- scale_for_ks(spp = "VR", file = "VR-DDT_dist-estimates.csv", 
                  data = scaled)
} 

if(median(dataset) == 0) { 

# Create Plot
create_plots(data = dataset, type = "in Muscle Tissue", contam = "DDT", 
             color = "darkslategray", path = "../../figures/vermilion-rockfish/", 
             file = "ddt_muscle_median0")
}

```

## CEM Generated Files
```{r}
# List of relevant files for DDT and VR
list_files <- list.files('../../data/CEMs/', pattern='ddt')
list_files <- list_files[grepl('scaled_VR', list_files)]

for( file in list_files ) { 
  dat <- read.csv(paste0('../../data/CEMS/', file))
  
  # First run will be without behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-noscale")
  
  dataset <- dat$total_tox
  
  if(median(dataset) != 0) { 
  
  # Scale to median
  
  scaled <- dataset/median(dataset)
  
  # Create Plot
  create_plots(data = scaled, type = "without behavioral data", contam = "DDT", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_ddt_no-behavioral"))
  
  # Scale for ks
  scaled_temp <- scale_for_ks(spp = "VR", 
                              file = paste0("VR-DDT-", 
                                            gsub("noscale", "notscaled", name),
                                            "_dist-estimates.csv"), 
                  data = scaled)
  
  
  # Save for later
  assign(name, scaled_temp)
  } 

  
  if(median(dataset) == 0) { 
  
  # Create Plot
  create_plots(data = dataset, type = "without behavioral data", contam = "DDT", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_ddt_no-behavioral_meadian0"))
  } 

  
  # Second run will be with behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-scale")
  
  dataset <- dat$total_behavioral_tox
  
  if(median(dataset) != 0) { 
  # Scale to median
  
  scaled <- dataset/median(dataset)
  
  # Create Plot
  create_plots(data = scaled, type = "with behavioral data", contam = "DDT", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_ddt_behavioral"))
  
  # Scale for KS test
  
  scaled_temp <- scale_for_ks(spp = "VR", 
                              file = paste0("VR-DDT-", 
                                            gsub("scale", "scaled", name),
                                            "_dist-estimates.csv"), 
                  data = scaled)
  
  # Save for later
  assign(name, scaled_temp)
  
  } 

  if(median(dataset) == 0) { 
  # Create Plot
  create_plots(data = dataset, type = "with behavioral data", contam = "DDT", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_ddt_behavioral_median0"))
  } 
  
}
```


## Run the KS tests
```{r} 
# With Zeros included for comparison

# Muscle vs all model runs
ks.test(ddt_tissue, `1mpermin-2min-noscale`)
ks.test(ddt_tissue, `1mpermin-5min-noscale`)
ks.test(ddt_tissue, `3mpermin-2min-noscale`)
ks.test(ddt_tissue, `3mpermin-5min-noscale`)
ks.test(ddt_tissue, `1mpermin-2min-scale`)
ks.test(ddt_tissue, `1mpermin-5min-scale`)
ks.test(ddt_tissue, `3mpermin-2min-scale`)
ks.test(ddt_tissue, `3mpermin-5min-scale`)
```

# PCB
## OCSD Data - Tissue
```{r}
# Tissue
filtered <- collect %>%
  filter(!is.na(PCB)) 

dataset <- filtered$PCB

if(median(dataset) != 0) { 

# Scale to median
scaled <- dataset/median(dataset)

# Create Plot
create_plots(data = scaled, type = "in Muscle Tissue", contam = "PCB", 
             color = "darkslategray", path = "../../figures/vermilion-rockfish/", 
             file = "pcb_muscle")

# scale for ks test

pcb_muscle <- scale_for_ks(spp = "VR", file = "VR-PCB_dist-estimates.csv", 
                  data = scaled)
} 

if(median(dataset) == 0) { 

# Create Plot
create_plots(data = dataset, type = "in Muscle Tissue", contam = "PCB", 
             color = "darkslategray", path = "../../figures/vermilion-rockfish/", 
             file = "pcb_muscle_median0")
}
```

## CEM Generated Files
```{r}
# List of relevant files for PCB and VR
list_files <- list.files('../../data/CEMs/', pattern='pcb')
list_files <- list_files[grepl('scaled_VR', list_files)]

for( file in list_files ) { 
  dat <- read.csv(paste0('../../data/CEMS/', file))
  
  # First run will be without behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-noscale")
  
  dataset <- dat$total_tox
  
  if(median(dataset) != 0) { 
  
  # Scale to median
  
  scaled <- dataset/median(dataset)
  
  # Create Plot
  create_plots(data = scaled, type = "without behavioral data", contam = "PCB", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_pcb_no-behavioral"))
  
  # Scale for ks
  scaled_temp <- scale_for_ks(spp = "VR", 
                              file = paste0("VR-PCB-", 
                                            gsub("noscale", "notscaled", name),
                                            "_dist-estimates.csv"), 
                  data = scaled)
  
  
  # Save for later
  assign(name, scaled_temp)
  } 

  
  if(median(dataset) == 0) { 
  
  # Create Plot
  create_plots(data = dataset, type = "without behavioral data", contam = "PCB", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_pcb_no-behavioral_meadian0"))
  } 

  
  # Second run will be with behavioral data
  name <- colsplit(file, "_", c("","","","",""))[,3]
  name <- paste(colsplit(name, "states-", c(""))[,2])
  name <- paste0(name, "-scale")
  
  dataset <- dat$total_behavioral_tox
  
  if(median(dataset) != 0) { 
  # Scale to median
  
  scaled <- dataset/median(dataset)
  
  # Create Plot
  create_plots(data = scaled, type = "with behavioral data", contam = "PCB", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_pcb_behavioral"))
  
  # Scale for KS test
  
  scaled_temp <- scale_for_ks(spp = "VR", 
                              file = paste0("VR-PCB-", 
                                            gsub("scale", "scaled", name),
                                            "_dist-estimates.csv"), 
                  data = scaled)
  
  # Save for later
  assign(name, scaled_temp)
  
  } 

  if(median(dataset) == 0) { 
  # Create Plot
  create_plots(data = dataset, type = "with behavioral data", contam = "PCB", 
             color = "dodgerblue4", path = "../../figures/vermilion-rockfish/", 
             file = paste0(name, "_pcb_behavioral_median0"))
  } 
  
}

```

## Run the KS tests
```{r} 
# With Zeros included for comparison

# Tissue vs all model runs
# ks.test(pcb_tissue, `1mpermin-2min-noscale`)
# ks.test(pcb_tissue, `1mpermin-5min-noscale`)
# ks.test(pcb_tissue, `3mpermin-2min-noscale`)
# ks.test(pcb_tissue, `3mpermin-5min-noscale`)
# ks.test(pcb_tissue, `1mpermin-2min-scale`)
# ks.test(pcb_tissue, `1mpermin-5min-scale`)
# ks.test(pcb_tissue, `3mpermin-2min-scale`)
# ks.test(pcb_tissue, `3mpermin-5min-scale`)
```

